[package]
name = "person_io"
version = "0.1.0"
authors = ["Chris Bailey <chris@ghostly.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
bincode = "1.2.1"
